import type { LucideIcon } from 'lucide-react'
import {
  ArrowDownToLine,
  ArrowUpFromLine,
  Minus,
  Database,
  GitMerge,
  GitFork,
  Zap,
  ArrowLeftRight,
  Snowflake,
  Flame,
  Filter,
  Droplets,
  ChevronsDown,
  Hammer,
  LayoutGrid,
  Wind,
  CircleDot,
  SlidersHorizontal,
  Cpu,
  Tag,
  PlusCircle,
} from 'lucide-react'
import type { UnitModelType } from '@/types'

export const UNIT_SYMBOLS: Record<UnitModelType, LucideIcon> = {
  Feeder:              ArrowDownToLine,
  FeederSink:          ArrowUpFromLine,
  Pipe:                Minus,
  Tank:                Database,
  Tie:                 GitMerge,
  Splitter:            GitFork,
  FlashTank:           Zap,
  FlashTank2:          Zap,
  HeatExchanger:       ArrowLeftRight,
  Cooler:              Snowflake,
  Heater:              Flame,
  Filter:              Filter,
  Washer:              Droplets,
  Thickener:           ChevronsDown,
  CrushingMill:        Hammer,
  Screen:              LayoutGrid,
  Cyclone:             Wind,
  Pump:                CircleDot,
  Valve:               SlidersHorizontal,
  GeneralController:   Cpu,
  PIDController:       SlidersHorizontal,
  SetTagController:    Tag,
  MakeupSource:        PlusCircle,
}
